apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: sh3z9zzxj-python
  janus-idp.io/tekton: sh3z9zzxj-python
  backstage.io/kubernetes-id: sh3z9zzxj-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: sh3z9zzxj-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
